import type { ConventionRegistry } from "../core/schema.js";
import { renderConventionsBody } from "./render-helpers.js";

/**
 * Render a GitHub Copilot instructions file (.github/copilot-instructions.md).
 *
 * Format: Plain markdown, no YAML frontmatter.
 * GitHub Copilot reads the entire file; HTML comment markers are used
 * for idempotent updates via writeWithMarkers.
 */
export function renderCopilotMd(
  registry: ConventionRegistry,
  confidenceThreshold: number
): string {
  const lines: string[] = [];

  lines.push("<!-- Generated by ez-context. Do not edit between markers. -->");
  lines.push("");
  lines.push("# Copilot Instructions");
  lines.push("");

  const bodyLines = renderConventionsBody(registry, confidenceThreshold);
  // Remove trailing empty line
  while (bodyLines.length > 0 && bodyLines[bodyLines.length - 1] === "") {
    bodyLines.pop();
  }
  lines.push(...bodyLines);

  return lines.join("\n") + "\n";
}
