import { afterEach, describe, expect, it } from "vitest";
import { rm, mkdtemp } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { renderCursorMdc } from "../../src/emitters/cursor-mdc.js";
import { renderCopilotMd } from "../../src/emitters/copilot-md.js";
import { renderSkillMd } from "../../src/emitters/skill-md.js";
import { renderRulesyncMd } from "../../src/emitters/rulesync-md.js";
import { renderRulerMd } from "../../src/emitters/ruler-md.js";
import { emit, FORMAT_EMITTER_MAP } from "../../src/emitters/index.js";
import { createRegistry, addConvention } from "../../src/core/registry.js";
import type { ConventionRegistry } from "../../src/core/schema.js";

// ---------------------------------------------------------------------------
// Fixture
// ---------------------------------------------------------------------------

function makeRegistry(): ConventionRegistry {
  let reg = createRegistry("/test/project");
  reg = {
    ...reg,
    stack: {
      language: "TypeScript",
      framework: "Express",
      testRunner: "Vitest",
      buildTool: "tsdown",
      packageManager: "bun",
    },
    architecture: {
      pattern: "layered",
      layers: ["core", "api", "db"],
    },
  };

  reg = addConvention(reg, {
    category: "naming",
    pattern: "camelCase for variables and functions",
    confidence: 0.9,
    evidence: [],
  });
  reg = addConvention(reg, {
    category: "testing",
    pattern: "test files in test/ directory",
    confidence: 0.85,
    evidence: [],
  });
  reg = addConvention(reg, {
    category: "stack",
    pattern: "build script",
    confidence: 0.95,
    evidence: [],
    metadata: { scriptName: "build", command: "tsdown" },
  });

  return reg;
}

// ---------------------------------------------------------------------------
// renderCursorMdc tests
// ---------------------------------------------------------------------------

describe("renderCursorMdc", () => {
  it("output starts with YAML frontmatter delimiter", () => {
    const reg = makeRegistry();
    const output = renderCursorMdc(reg, 0.7);
    expect(output).toMatch(/^---\n/);
  });

  it("frontmatter contains alwaysApply: true", () => {
    const reg = makeRegistry();
    const output = renderCursorMdc(reg, 0.7);
    expect(output).toContain("alwaysApply: true");
  });

  it("frontmatter contains globs as empty string (not null or omitted)", () => {
    const reg = makeRegistry();
    const output = renderCursorMdc(reg, 0.7);
    // js-yaml renders empty string as 'globs: ""\n' or "globs: ''"
    expect(output).toMatch(/globs: ['"]{0,1}['"]{0,1}/);
    // Crucially, globs field IS present
    expect(output).toContain("globs:");
  });

  it("frontmatter contains description field", () => {
    const reg = makeRegistry();
    const output = renderCursorMdc(reg, 0.7);
    expect(output).toContain("description:");
  });

  it("frontmatter is closed before markdown body", () => {
    const reg = makeRegistry();
    const output = renderCursorMdc(reg, 0.7);
    // Should have opening ---, content, closing ---
    const parts = output.split("---\n");
    expect(parts.length).toBeGreaterThanOrEqual(3);
  });

  it("markdown body contains stack info", () => {
    const reg = makeRegistry();
    const output = renderCursorMdc(reg, 0.7);
    expect(output).toContain("TypeScript");
    expect(output).toContain("## Stack");
  });

  it("markdown body contains conventions", () => {
    const reg = makeRegistry();
    const output = renderCursorMdc(reg, 0.7);
    expect(output).toContain("camelCase for variables and functions");
  });
});

// ---------------------------------------------------------------------------
// renderCopilotMd tests
// ---------------------------------------------------------------------------

describe("renderCopilotMd", () => {
  it("output is plain markdown (no YAML frontmatter)", () => {
    const reg = makeRegistry();
    const output = renderCopilotMd(reg, 0.7);
    expect(output).not.toMatch(/^---\n/);
  });

  it("output starts with HTML comment header", () => {
    const reg = makeRegistry();
    const output = renderCopilotMd(reg, 0.7);
    expect(output).toMatch(/^<!-- Generated by ez-context/);
  });

  it("output contains Copilot Instructions heading", () => {
    const reg = makeRegistry();
    const output = renderCopilotMd(reg, 0.7);
    expect(output).toContain("# Copilot Instructions");
  });

  it("output contains stack and conventions", () => {
    const reg = makeRegistry();
    const output = renderCopilotMd(reg, 0.7);
    expect(output).toContain("TypeScript");
    expect(output).toContain("camelCase for variables and functions");
  });
});

// ---------------------------------------------------------------------------
// renderSkillMd tests
// ---------------------------------------------------------------------------

describe("renderSkillMd", () => {
  it("output starts with YAML frontmatter", () => {
    const reg = makeRegistry();
    const output = renderSkillMd(reg, 0.7);
    expect(output).toMatch(/^---\n/);
  });

  it('frontmatter contains name: ez-context', () => {
    const reg = makeRegistry();
    const output = renderSkillMd(reg, 0.7);
    expect(output).toContain("name: ez-context");
  });

  it("frontmatter contains description field", () => {
    const reg = makeRegistry();
    const output = renderSkillMd(reg, 0.7);
    expect(output).toContain("description:");
  });

  it("description is under 1024 characters", () => {
    const reg = makeRegistry();
    const output = renderSkillMd(reg, 0.7);
    // Extract YAML between first --- markers
    const yamlMatch = output.match(/^---\n([\s\S]*?)\n---/);
    expect(yamlMatch).not.toBeNull();
    const yamlBlock = yamlMatch?.[1] ?? "";
    // description field value
    const descMatch = yamlBlock.match(/description: (.+)/);
    expect(descMatch).not.toBeNull();
    const desc = (descMatch?.[1] ?? "").trim().replace(/^['"]|['"]$/g, "");
    expect(desc.length).toBeLessThanOrEqual(1024);
  });

  it("body contains conventions", () => {
    const reg = makeRegistry();
    const output = renderSkillMd(reg, 0.7);
    expect(output).toContain("camelCase for variables and functions");
  });
});

// ---------------------------------------------------------------------------
// renderRulesyncMd tests
// ---------------------------------------------------------------------------

describe("renderRulesyncMd", () => {
  it("output starts with YAML frontmatter", () => {
    const reg = makeRegistry();
    const output = renderRulesyncMd(reg, 0.7);
    expect(output).toMatch(/^---\n/);
  });

  it("frontmatter contains targets field", () => {
    const reg = makeRegistry();
    const output = renderRulesyncMd(reg, 0.7);
    expect(output).toContain("targets:");
  });

  it("frontmatter targets is a YAML list", () => {
    const reg = makeRegistry();
    const output = renderRulesyncMd(reg, 0.7);
    // YAML list items start with "- "
    expect(output).toMatch(/targets:\n(\s*- .+\n)+/);
  });

  it("body contains conventions", () => {
    const reg = makeRegistry();
    const output = renderRulesyncMd(reg, 0.7);
    expect(output).toContain("camelCase for variables and functions");
  });
});

// ---------------------------------------------------------------------------
// renderRulerMd tests
// ---------------------------------------------------------------------------

describe("renderRulerMd", () => {
  it("output is plain markdown (no YAML frontmatter)", () => {
    const reg = makeRegistry();
    const output = renderRulerMd(reg, 0.7);
    expect(output).not.toMatch(/^---\n/);
  });

  it("output starts with a heading", () => {
    const reg = makeRegistry();
    const output = renderRulerMd(reg, 0.7);
    expect(output).toMatch(/^# /);
  });

  it("body contains stack and conventions", () => {
    const reg = makeRegistry();
    const output = renderRulerMd(reg, 0.7);
    expect(output).toContain("TypeScript");
    expect(output).toContain("camelCase for variables and functions");
  });
});

// ---------------------------------------------------------------------------
// FORMAT_EMITTER_MAP tests
// ---------------------------------------------------------------------------

describe("FORMAT_EMITTER_MAP", () => {
  it("contains all 7 output formats", () => {
    const formats = Object.keys(FORMAT_EMITTER_MAP);
    expect(formats).toContain("claude");
    expect(formats).toContain("agents");
    expect(formats).toContain("cursor");
    expect(formats).toContain("copilot");
    expect(formats).toContain("skills");
    expect(formats).toContain("rulesync");
    expect(formats).toContain("ruler");
  });

  it("cursor entry uses direct write strategy", () => {
    expect(FORMAT_EMITTER_MAP.cursor.strategy).toBe("direct");
  });

  it("claude entry uses markers write strategy", () => {
    expect(FORMAT_EMITTER_MAP.claude.strategy).toBe("markers");
  });

  it("cursor filename includes .mdc extension under .cursor/rules/", () => {
    expect(FORMAT_EMITTER_MAP.cursor.filename).toMatch(/\.mdc$/);
    expect(FORMAT_EMITTER_MAP.cursor.filename).toContain(".cursor");
  });
});

// ---------------------------------------------------------------------------
// emit() with formats array tests
// ---------------------------------------------------------------------------

describe("emit() with formats", () => {
  const tempDirs: string[] = [];

  afterEach(async () => {
    for (const dir of tempDirs) {
      if (existsSync(dir)) {
        await rm(dir, { recursive: true, force: true });
      }
    }
    tempDirs.length = 0;
  });

  async function makeTmpDir(): Promise<string> {
    const dir = await mkdtemp(path.join(os.tmpdir(), "ez-context-fmt-test-"));
    tempDirs.push(dir);
    return dir;
  }

  it("dryRun with formats cursor+ruler returns both in rendered map", async () => {
    const reg = makeRegistry();
    const result = await emit(reg, {
      outputDir: "/nonexistent",
      dryRun: true,
      formats: ["cursor", "ruler"],
    });

    expect(result.rendered).toHaveProperty("cursor");
    expect(result.rendered).toHaveProperty("ruler");
    expect(result.filesWritten).toEqual([]);
  });

  it("dryRun cursor render starts with YAML frontmatter", async () => {
    const reg = makeRegistry();
    const result = await emit(reg, {
      outputDir: "/nonexistent",
      dryRun: true,
      formats: ["cursor"],
    });

    expect(result.rendered["cursor"]).toMatch(/^---\n/);
    expect(result.rendered["cursor"]).toContain("alwaysApply: true");
  });

  it("backward compat: no formats defaults to claude+agents", async () => {
    const reg = makeRegistry();
    const result = await emit(reg, {
      outputDir: "/nonexistent",
      dryRun: true,
    });

    expect(result.claudeMd).toContain("# Project Context");
    expect(result.agentsMd).toContain("# AGENTS.md");
    expect(result.rendered).toHaveProperty("claude");
    expect(result.rendered).toHaveProperty("agents");
    expect(result.filesWritten).toEqual([]);
  });

  it("backward compat claudeMd/agentsMd fields populated when those formats requested", async () => {
    const reg = makeRegistry();
    const result = await emit(reg, {
      outputDir: "/nonexistent",
      dryRun: true,
      formats: ["claude", "agents"],
    });

    expect(result.claudeMd).toBe(result.rendered["claude"]);
    expect(result.agentsMd).toBe(result.rendered["agents"]);
  });

  it("claudeMd/agentsMd are empty string when formats excludes them", async () => {
    const reg = makeRegistry();
    const result = await emit(reg, {
      outputDir: "/nonexistent",
      dryRun: true,
      formats: ["cursor"],
    });

    expect(result.claudeMd).toBe("");
    expect(result.agentsMd).toBe("");
  });

  it("writes .cursor/rules/ directory when format is cursor", async () => {
    const reg = makeRegistry();
    const tmpDir = await makeTmpDir();

    const result = await emit(reg, {
      outputDir: tmpDir,
      dryRun: false,
      formats: ["cursor"],
    });

    const cursorRulesDir = path.join(tmpDir, ".cursor", "rules");
    expect(existsSync(cursorRulesDir)).toBe(true);
    expect(result.filesWritten).toHaveLength(1);
    expect(result.filesWritten[0]).toMatch(/ez-context\.mdc$/);
  });

  it("creates nested .skills/ez-context/ directory for skills format", async () => {
    const reg = makeRegistry();
    const tmpDir = await makeTmpDir();

    const result = await emit(reg, {
      outputDir: tmpDir,
      dryRun: false,
      formats: ["skills"],
    });

    const skillsDir = path.join(tmpDir, ".skills", "ez-context");
    expect(existsSync(skillsDir)).toBe(true);
    expect(result.filesWritten[0]).toMatch(/SKILL\.md$/);
  });

  it("writes correct number of files for multi-format emit", async () => {
    const reg = makeRegistry();
    const tmpDir = await makeTmpDir();

    const result = await emit(reg, {
      outputDir: tmpDir,
      dryRun: false,
      formats: ["claude", "cursor", "ruler"],
    });

    expect(result.filesWritten).toHaveLength(3);
  });

  it("copilot format creates .github/ parent directory when it does not exist", async () => {
    const reg = makeRegistry();
    const tmpDir = await makeTmpDir();

    // Sanity-check: .github does not exist yet
    expect(existsSync(path.join(tmpDir, ".github"))).toBe(false);

    const result = await emit(reg, {
      outputDir: tmpDir,
      dryRun: false,
      formats: ["copilot"],
    });

    expect(existsSync(path.join(tmpDir, ".github"))).toBe(true);
    expect(result.filesWritten).toHaveLength(1);
    expect(result.filesWritten[0]).toMatch(/copilot-instructions\.md$/);
  });
});
